# docker-compose.yml

version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    # --- ADICIONADO PARA ROBUSTEZ ---
    # Garante que este serviço também leia o arquivo .env
    env_file:
      - ./.env
    # ---------------------------------
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: .
    container_name: gestao_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  mysql-data: